services:
  front:
    build:
      context: front/
    container_name: front
    restart: unless-stopped
    depends_on:
      - fastapi
    ports:
     - "3000:3000"
  fastapi:
    build:
      context: back/
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
  celery:
    build:
      dockerfile: celery-dockerfile
      context: back/
    restart: unless-stopped
    container_name: celery
    depends_on:
      - fastapi
      - redis
